--CRIACAO DAS TABELAS 
CREATE TABLE CLIENTE (
	CPF VARCHAR(11) PRIMARY KEY, 
	NOME VARCHAR (50) UNIQUE
);

CREATE TABLE ENDERECO(
	ID SERIAL PRIMARY KEY, 
	ENDERECO VARCHAR(100), 
	CPF VARCHAR (11) REFERENCES CLIENTE(CPF),
	UNIQUE(ENDERECO, CPF )
);

CREATE TABLE TELEFONE(
	CPF VARCHAR (11) REFERENCES CLIENTE(CPF),
	TELEFONE VARCHAR(11), 
	PRIMARY KEY (CPF, TELEFONE)
);

CREATE TABLE STATUS(
	ID SERIAL PRIMARY KEY,
	STATUS VARCHAR(20)
);

CREATE TABLE VENDA(
	ID SERIAL PRIMARY KEY, 
	DATA DATE ,
	CPF VARCHAR(11) REFERENCES CLIENTE(CPF),
	STATUS_ID INT REFERENCES STATUS(ID)
); 



CREATE TABLE ITEM(
	ID SERIAL PRIMARY KEY, 
	NOME VARCHAR (30),
	DESCRICAO VARCHAR (50),
	VALOR MONEY
);


CREATE TABLE ITEM_X_VENDA(
	ID_ITEM INT REFERENCES ITEM (ID), 
	ID_VENDA INT REFERENCES VENDA(ID),
	QTD INT
);

ALTER TABLE ITEM_X_VENDA ADD CONSTRAINT PK_ITEM_VENDA PRIMARY KEY (ID_VENDA, ID_ITEM);


--POPULANDO TABELAS
INSERT INTO STATUS (STATUS) VALUES ('APROVADO'), ('AGUARDANDO PAGMANTO'), ('CONCLUIDO');

INSERT INTO ITEM (NOME, DESCRICAO, VALOR) 
VALUES ('BISCOITO', 'RECHEADO' , 2),
 		('BOLO', 'RECHEADO' , 15),
		('REFRI', 'LITRO' , 8)
		
		
INSERT INTO CLIENTE (CPF,NOME) VALUES ('1','VITOR'), ('2','SUZANA'), ('3','GIOVANI');

INSERT INTO TELEFONE (CPF, TELEFONE) VALUES ('1','123');

INSERT INTO ENDERECO (CPF, ENDERECO) VALUES ('1', ' RUA DD');


INSERT INTO VENDA (DATA, CPF, STATUS_ID) VALUES ('2023-06-15', '1', 1);

INSERT INTO ITEM_x_VENDA (ID_ITEM, ID_VENDA,QTD) 
VALUES (1, 1, 5),
(2, 1, 2),
(3, 1, 3)


INSERT INTO VENDA (DATA,CPF, STATUS_ID) VALUES ('2023-06-14','2', 2);

INSERT INTO ITEM_x_VENDA (ID_ITEM, ID_VENDA,QTD) 
VALUES (1, 2, 5),
(2, 2, 5),
(3, 2, 3)


INSERT INTO VENDA (DATA,CPF, STATUS_ID) VALUES ('2023-06-14','3', 2);

INSERT INTO ITEM_x_VENDA (ID_ITEM, ID_VENDA,QTD) 
VALUES (1, 3, 5),
(2, 3, 5),
(3, 3, 3)


--GERACAO DE RELATORIOS 

SELECT V.ID,
	   DATA, 
	   STATUS, 
	   C.CPF,
	   NOME, 
	   TELEFONE,
	   ENDERECO
FROM VENDA V
INNER JOIN CLIENTE C ON V.CPF = C.CPF
INNER JOIN STATUS S ON S.ID = V.STATUS_ID
LEFT JOIN TELEFONE T ON T.CPF= C.CPF
LEFT JOIN ENDERECO E ON E.CPF = C.CPF


(SELECT V.ID
	   DATA,
	   C.CPF, 
	   C.NOME, 
	   STATUS,
	   I.NOME,
	   I.DESCRICAO,
	   X.QTD, 
	   I.VALOR, 
	   X.QTD * I.VALOR AS TOTAL
FROM VENDA V
INNER JOIN STATUS S ON S.ID = V.STATUS_ID
INNER JOIN ITEM_X_VENDA X ON X.ID_VENDA = V.ID
INNER JOIN ITEM I ON I.ID = X.ID_ITEM
INNER JOIN CLIENTE C ON C.CPF = V.CPF
WHERE V.ID = 1)




(SELECT V.ID
	   DATA,
	   C.CPF, 
	   C.NOME, 
	   STATUS,
	   I.NOME,
	   I.DESCRICAO,
	   X.QTD, 
	   I.VALOR, 
	   X.QTD * I.VALOR AS TOTAL
FROM VENDA V
INNER JOIN STATUS S ON S.ID = V.STATUS_ID
INNER JOIN ITEM_X_VENDA X ON X.ID_VENDA = V.ID
INNER JOIN ITEM I ON I.ID = X.ID_ITEM
INNER JOIN CLIENTE C ON C.CPF = V.CPF
WHERE V.ID = 3)



 SELECT SUM(TOTAL) FROM (SELECT 
	   X.QTD * I.VALOR AS TOTAL
FROM  ITEM_X_VENDA X 
INNER JOIN ITEM I ON I.ID = X.ID_ITEM
WHERE X.ID_VENDA = 3) AS RESULTADO 
