
--TABELA BASE
CREATE TABLE ALUNO(
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(20) UNIQUE NOT NULL, 
	CURSO VARCHAR(20) NOT NULL,
	OBS TEXT
)

--INSERT 
INSERT INTO ALUNO (NOME, CURSO) VALUES ('mANUEL', 'php')

INSERT INTO ALUNO  VALUES (7, 'fABIOLA', 'Analise sistemas', 'TESTE')

--SELECTS 

SELECT * FROM ALUNO WHERE CURSO != 'NUTRICAO' 

SELECT * FROM ALUNO
WHERE NOME = 'vITOR '

SELECT * FROM ALUNO
WHERE NOME LIKE '%N%'

SELECT * FROM ALUNO
ORDER BY ID  DESC 


--UPDATE

UPDATE ALUNO 
SET CURSO = 'ANALISE SISTEMAS'
WHERE CURSO = 'Analise sistemas'


--TRANSACAO 
BEGIN TRANSACTION
ROLLBACK 

COMMIT

--DELETE 

DELETE FROM ALUNO 
WHERE ID = 7



--SELECT FILTRO COMPOSTO 
SELECT * FROM ALUNO
WHERE CURSO = 'NUTRICAO' AND OBS = 'MATRICULADA'  

SELECT * FROM ALUNO
WHERE CURSO = 'ANALISE SISTEMAS' OR OBS = 'MATRICULADA' 


-- DISTINCAO

SELECT DISTINCT(CURSO), NOME FROM ALUNO 

SELECT DISTINCT(CURSO) FROM ALUNO 

SELECT CURSO, NOME FROM ALUNO 
GROUP BY  CURSO, NOME


