
CREATE TABLE CLIENTES(
ID INT PRIMARY KEY,
NOME VARCHAR(50)
);

CREATE TABLE TELEFONES(
TELEFONE VARCHAR(11) NOT NULL,
ID_CLIENTE INT REFERENCES CLIENTES(ID) NOT NULL 
);
ALTER TABLE TELEFONES ADD PRIMARY KEY (TELEFONE, ID_CLIENTE);


INSERT INTO CLIENTES (ID, NOME) VALUES (1, 'Lucas'), (2, 'Vanessa'), (3, 'Graziela');

									   
INSERT INTO TELEFONES (TELEFONE, ID_CLIENTE) VALUES ('12345', 1),('45641', 3), ('98765', 3);


SELECT * FROM CLIENTES;
SELECT * FROM TELEFONES ;

-- JOIN BASICO 
SELECT * FROM CLIENTES
INNER JOIN TELEFONES ON CLIENTES.ID = TELEFONES.ID_CLIENTE

-- JOIN E INNER JOINE É A MESMA COISA 
--JOIN COM FILTROS
SELECT * FROM CLIENTES
INNER JOIN TELEFONES ON CLIENTES.ID = TELEFONES.ID_CLIENTE
WHERE CLIENTES.ID = 3
ORDER BY TELEFONES.TELEFONE DESC -- DESC - ORDENA DE FORMA DESCRESENTE \ ASC - ORDENA DE FORMA CRSCENTE - POR PADRãO O ORDER BY UTILIZA ASC


--LEFT JOIN
SELECT * FROM CLIENTES
LEFT JOIN TELEFONES ON CLIENTES.ID = TELEFONES.ID_CLIENTE


--RIGHT JOIN
SELECT * FROM TELEFONES
RIGHT JOIN CLIENTES ON CLIENTES.ID = TELEFONES.ID_CLIENTE




--LEFT JOIN - TRAZENDO  APENAS OS VALORES QUE NÃO TEM JNA JUNÇÃO
SELECT * FROM CLIENTES
LEFT JOIN TELEFONES ON CLIENTES.ID = TELEFONES.ID_CLIENTE
WHERE TELEFONES.TELEFONE IS NULL